# Funding links for VisualAssist
# Learn more: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
# github: yadava5

# Custom links (update when available)
# ko_fi: yadava5
# buy_me_a_coffee: yadava5

# Placeholder - uncomment and configure when ready
custom: []
