name: 🐛 Bug Report
description: Report a bug or unexpected behavior in VisualAssist
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open the app
        2. Navigate to '...'
        3. Tap on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Which mode were you using?
      options:
        - Navigation Mode
        - Object Awareness Mode
        - Text Reading Mode
        - Settings
        - Home Screen
        - Other
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: Which iPhone are you using?
      placeholder: "e.g., iPhone 15 Pro"
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      placeholder: "e.g., iOS 17.4"
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      placeholder: "e.g., 0.1.0-beta"
    validations:
      required: true

  - type: dropdown
    id: accessibility
    attributes:
      label: VoiceOver Enabled?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Add any relevant logs, crash reports, or screenshots.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before.
          required: true
