name: ✨ Feature Request
description: Suggest a new feature or enhancement for VisualAssist
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve VisualAssist? We'd love to hear it! Please describe your feature request below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing.
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature or solution.
      placeholder: "It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Navigation & Obstacle Detection
        - Object Recognition
        - Text Reading (OCR)
        - Voice Commands
        - Haptic Feedback
        - Spatial Audio
        - Accessibility
        - Settings & Customization
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: How would this help you?
      options:
        - Critical for daily use
        - Would significantly improve experience
        - Nice to have
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have searched existing issues and this feature hasn't been requested before.
          required: true
